[project]
name = 'Democratic-Autocracy-Consensus-Algorithm'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.consensus-building-decision-elimination-service]
path = 'contracts/consensus-building-decision-elimination-service.clar'
clarity_version = 3
epoch = 'latest'

[contracts.crowd-sourced-individual-opinion-generator]
path = 'contracts/crowd-sourced-individual-opinion-generator.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
